# Generated by Django 2.2.6 on 2019-10-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedofr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='plant_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seedofr'),
        ),
    ]
