# Generated by Django 2.2.6 on 2019-10-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedofr', '0002_auto_20191028_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Watson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier_id', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('_class', models.CharField(blank=True, max_length=128, null=True)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='plant_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
